// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Health check used to validate the IPC bridge end to end.
 */
async ping() : Promise<string> {
    return await TAURI_INVOKE("ping");
},
async buildSilenceEdl(asset: Asset, silences: TimeRange[], settings: SilenceSettings) : Promise<Result<Edl, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_silence_edl", { asset, silences, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importMedia(path: string) : Promise<Result<AssetSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_media", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async projectStatus() : Promise<Result<ProjectStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replaces the EDL with the speech parts of `asset_id`.
 */
async autoCut(assetId: string, settings: SilenceSettings, noiseDb: number | null) : Promise<Result<EdlSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auto_cut", { assetId, settings, noiseDb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editEdl(ops: EdlOp[]) : Promise<Result<EdlSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_edl", { ops }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reverts the last change to the timeline, the user's or an agent's.
 */
async undo() : Promise<Result<HistoryStep, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async redo() : Promise<Result<HistoryStep, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Frame of the edit at `time`, as a PNG data URL ready for an `<img>`.
 */
async previewFrame(time: number, maxWidth: number) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_frame", { time, maxWidth }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Playback proxy of an asset. The front plays it through the asset protocol.
 */
async prepareProxy(assetId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_proxy", { assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareThumbnails(assetId: string) : Promise<Result<ThumbnailStrip, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_thumbnails", { assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prepareWaveform(assetId: string) : Promise<Result<WaveformPeaks, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_waveform", { assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transcribes an asset (local Whisper). The first use of a model downloads it, so this can
 * take minutes; a transcript already computed comes back at once.
 */
async transcribe(assetId: string, language: string | null, model: string | null) : Promise<Result<TranscriptReport, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe", { assetId, language, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The transcript of an asset if one exists, without starting a transcription.
 */
async cachedTranscript(assetId: string) : Promise<Result<TranscriptReport | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cached_transcript", { assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the edit says, sentence by sentence, from the transcripts already computed.
 */
async editTranscript() : Promise<Result<EditTranscript, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_transcript") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cuts a phrase of `asset_id`'s transcript (said around `start..end` in the source) out of
 * the edit, at word precision.
 */
async cutPhrase(assetId: string, start: number, end: number, text: string) : Promise<Result<TextEditReport, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cut_phrase", { assetId, start, end, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFillers() : Promise<Result<TextEditReport, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_fillers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeRetakes() : Promise<Result<TextEditReport, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_retakes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes the project to `path` and keeps that file up to date from now on.
 */
async saveProject(path: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openProject(path: string) : Promise<Result<OpenReport, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async newProject() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renders to `output`, or next to the first source when none is given. Every cut gets short
 * audio fades; `normalize_audio` also levels the loudness to -14 LUFS.
 */
async renderStart(draft: boolean, output: string | null, normalizeAudio: boolean) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_start", { draft, output, normalizeAudio }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderStatus(jobId: string) : Promise<Result<JobStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_status", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderCancel(jobId: string) : Promise<Result<JobStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_cancel", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
agentActivity: AgentActivity
}>({
agentActivity: "agent-activity"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * One step of what an agent is doing, for the virtual cursor.
 */
export type AgentActivity = { tool: string; phase: AgentPhase; label: string; index: number | null; time: number | null; changes_project: boolean }
export type AgentPhase = 
/**
 * The agent just asked for the action; the UI has time to move a cursor there.
 */
"started" | "finished" | "failed"
/**
 * Error surfaced to the front. Serialized as `{ kind, message }` so the UI can
 * branch on `kind` without parsing text.
 */
export type AppError = { kind: "invalidInput"; message: string } | { kind: "internal"; message: string }
export type Asset = { id: AssetId; path: string; duration: number; 
/**
 * Screen recordings and silent clips have no audio track. Project files written before
 * this field existed could only hold assets with sound.
 */
has_audio?: boolean }
/**
 * Stable identifier of an imported asset (content hash, see cache rules in CLAUDE.md).
 */
export type AssetId = string
export type AssetSummary = { id: string; path: string; duration: number; 
/**
 * `false` for silent clips: nothing to detect, transcribe or draw as a waveform.
 */
has_audio: boolean; width: number | null; height: number | null; fps: number | null }
/**
 * One kept portion of a source asset.
 */
export type Cut = { asset: AssetId; range: TimeRange }
export type CutSummary = { index: number; asset: string; start: number; end: number; duration: number; 
/**
 * Where this cut begins on the edited timeline.
 */
timeline_start: number }
/**
 * One sentence of the edit, at its position on the edited timeline.
 */
export type EditLine = { start: number; end: number; text: string }
export type EditTranscript = { lines: EditLine[]; full_text: string; 
/**
 * Every clip has word timings. Otherwise some lines are whole whisper phrases, whose
 * bounds can be a second off.
 */
word_level: boolean; 
/**
 * Assets of the edit that have sound but no transcript yet: call `transcribe` on them.
 */
untranscribed: string[] }
/**
 * Edit decision list: the ordered cuts that make up the final video.
 */
export type Edl = { cuts: Cut[] }
/**
 * One edit. Indices refer to the EDL as it is when the op runs, so a batch is
 * applied in order.
 */
export type EdlOp = 
/**
 * Removes the cut at `index`.
 */
{ op: "delete"; index: number } | 
/**
 * Changes the source range of a cut (absolute source seconds).
 */
{ op: "trim"; index: number; start: number; end: number } | 
/**
 * Splits a cut in two at source time `at`, which must fall strictly inside it.
 */
{ op: "split"; index: number; at: number } | 
/**
 * Moves the cut at `from` so that it ends up at position `to`.
 */
{ op: "move"; from: number; to: number } | 
/**
 * Inserts a new cut before position `index` (`index == len` appends).
 */
{ op: "insert"; index: number; asset: AssetId; start: number; end: number } | 
/**
 * Removes every cut.
 */
{ op: "clear" } | 
/**
 * Removes the source range `start..end` of `asset` wherever the EDL plays it, trimming or
 * splitting the cuts it overlaps. How text-based edits (a sentence, a filler) are applied.
 */
{ op: "remove_range"; asset: AssetId; start: number; end: number }
export type EdlSummary = { cuts: CutSummary[]; total_duration: number; 
/**
 * Names of the changes `undo` and `redo` would revert or re-apply.
 */
history: HistoryStatus }
/**
 * What can be undone or redone next, for menus and for agents.
 */
export type HistoryStatus = { undo: string | null; redo: string | null }
/**
 * Result of `undo` / `redo`.
 */
export type HistoryStep = { 
/**
 * The change that was reverted (undo) or applied again (redo).
 */
change: string; edl: EdlSummary }
export type JobStatus = ({ state: "running" } | { state: "done"; size_bytes: number } | { state: "failed"; error: string } | { state: "cancelled" }) & { id: string; output: string; 
/**
 * Fraction in `[0, 1]`.
 */
progress: number; elapsed_secs: number }
export type OpenReport = { assets: number; cuts: number; 
/**
 * Source files that no longer exist at their recorded path.
 */
missing_files: string[] }
export type ProjectStatus = { assets: AssetSummary[]; edl: EdlSummary; project_file: string | null }
/**
 * User-facing silence-removal settings, in seconds.
 */
export type SilenceSettings = { 
/**
 * Pauses shorter than this between kept segments are bridged.
 */
max_gap: number; 
/**
 * Padding kept around each segment so words aren't clipped.
 */
margin: number; 
/**
 * Kept segments shorter than this are discarded.
 */
min_segment: number }
/**
 * A piece of speech removed (or that would be removed) from the edit.
 */
export type TextCut = { text: string; 
/**
 * Where it was on the edited timeline before the change.
 */
timeline_start: number; duration: number; 
/**
 * For a failed take: the retry that is kept instead.
 */
replaced_by: string | null }
export type TextEditReport = { removed: TextCut[]; removed_seconds: number; 
/**
 * `false` for a dry run: nothing was changed.
 */
applied: boolean; edl: EdlSummary }
/**
 * Thumbnails of one asset laid out side by side in a single image.
 */
export type ThumbnailStrip = { path: string; 
/**
 * Seconds between two thumbnails: tile `i` shows the frame at `i * step`.
 */
step: number; tiles: number; tile_width: number; tile_height: number }
/**
 * Half-open interval `[start, end)` in seconds on a source timeline.
 */
export type TimeRange = { start: number; end: number }
export type TranscriptEntry = { start: number; end: number; text: string }
export type TranscriptReport = { asset: string; model: string; language: string; word_timestamps: boolean; cached: boolean; segments: TranscriptEntry[]; full_text: string }
/**
 * One byte per `1 / peaks_per_second` seconds, base64 encoded (a few tens of KB).
 */
export type WaveformPeaks = { peaks_per_second: number; base64: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
