// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Health check used to validate the IPC bridge end to end.
 */
async ping() : Promise<string> {
    return await TAURI_INVOKE("ping");
},
async buildSilenceEdl(asset: Asset, silences: TimeRange[], settings: SilenceSettings) : Promise<Result<Edl, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_silence_edl", { asset, silences, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Error surfaced to the front. Serialized as `{ kind, message }` so the UI can
 * branch on `kind` without parsing text.
 */
export type AppError = { kind: "invalidInput"; message: string } | { kind: "internal"; message: string }
export type Asset = { id: AssetId; path: string; duration: number }
/**
 * Stable identifier of an imported asset (content hash, see cache rules in CLAUDE.md).
 */
export type AssetId = string
/**
 * One kept portion of a source asset.
 */
export type Cut = { asset: AssetId; range: TimeRange }
/**
 * Edit decision list: the ordered cuts that make up the final video.
 */
export type Edl = { cuts: Cut[] }
/**
 * User-facing silence-removal settings, in seconds.
 */
export type SilenceSettings = { 
/**
 * Pauses shorter than this between kept segments are bridged.
 */
max_gap: number; 
/**
 * Padding kept around each segment so words aren't clipped.
 */
margin: number; 
/**
 * Kept segments shorter than this are discarded.
 */
min_segment: number }
/**
 * Half-open interval `[start, end)` in seconds on a source timeline.
 */
export type TimeRange = { start: number; end: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
