[package]
name = "autolad-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
autolad-core = { path = "../core" }
blake3.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true

